### ISSUE TITLE
Account Creator

### ISSUE THREAD

**Issue by TomazMPP** [victorgare/tribalwars#10]
.

**Comment by victorgare** [comment]
Esse script ainda funciona? ultima atualização dele ja faz 4 anos, talvez a pagina tenha alterado e o script não encontre o que precisa

**Comment by TomazMPP** [comment]
Oi, funciona. Fiz algumas alterações e coloquei um delay, pois ele tava alterando constantemente os logins e senhas antes de processar o carregamento do botão. Porém não está funcionando no tampermonkey, só consegui fazer funcionar no firemonkey do firefox. Pode me ajudar?

**Comment by victorgare** [comment]
No tampermonkey, ele apresenta algum erro no console?
