### ISSUE TITLE
Problema do script Continuos Recruting

### ISSUE THREAD

**Issue by MrGui09** [victorgare/tribalwars#11]
O script não está funcionando.
Tem dois erros, um na linha 134 e outro na linha 135.
Poderiam resolver esse problema?

**Comment by victorgare** [comment]
Essas linhas fazem parte de uma função de aleatoriedade do tempo, como esta seus parametros pra essa linha?

var altAldTempo = aleatorio(10000, 100000);

**Comment by kenixx** [comment]
Nao esta a funcionar, vou à aba recrutar e nao aparece nada nem que o script esta a rodar
