### ISSUE TITLE
PRoblema - Planejador de Comandos

### ISSUE THREAD

**Issue by Lucasnmaia** [victorgare/tribalwars#12]
Boa tarde,
O script Planejador de Comandos não está rodando, sabe o que pode ser?

**Comment by victorgare** [comment]
Estou a algum tempo dem jogar, mas a ultima vez que alguns amigos me falaram, havia mudado um pouco a estrutura do DOM do jogo, sendo assim, precisava atualizar os selectors, nao sei se esse ainda é o problema
