### ISSUE TITLE
please fixed? thanx

### ISSUE THREAD

**Issue by Deswer60871** [victorgare/tribalwars#6]
`javascript:function AtaqueAS()

**Comment by victorgare** [comment]
Voce corrigiu o script? Se sim, faz um pull request disso e eu aprovo

**Comment by Deswer60871** [comment]
im nod programing

**Comment by Smont** [comment]
@victorgare 
alguma previsão de atualizar os scripts?

**Comment by victorgare** [comment]
@Smont eu não estou jogando ja faz algum tempo, então não tenho previsão pra arrumar os scripts, se você quiser fazer alguma correção, abre um PR que eu fico muito feliz em fazer o merge e colocar os devidos créditos

**Comment by C7696** [comment]
Fala Victor, só de boa... cara seus scripts é muito massa, mas estão desatualizados, estou atualizando alguns.. e criando algum. Topa se juntar a mim, em novo projeto?

**Comment by victorgare** [comment]
Opa @C7696 eu não estava jogando, estou voltando a jogar agora, provavelmente vou atualizar alguns conforme for precisando, se tiver corrigido, senta-se livre pra abrir um PR :D

**Comment by C7696** [comment]
Ragnar Vortigern, mundo 124, me chama lá, bora conversar... eu criei uma coisa... tenho "boot" , bora conversar, quem sabe a gente consegue fazer algo massa juntos e ganhar uma grana extra. O que acha?

**Comment by victorgare** [comment]
Already fixed the old farm script and added a new one with new features
